### ISSUE TITLE
Support wwm variables in Launch keybindings

### ISSUE THREAD

**Issue by TimUntersberger** [TimUntersberger/wwm#35]
Example:

You want to define a keybinding that opens the wwm config in your favorite editor.

Right now you have to know where the wwm config is and whenever this changes in the future you will have to update the keybinding.

After introducing this you can just use the variable instead of the hardcoded path.

The keybinding would then look something like this:

```yaml
type: Launch
key: Control+Alt+,
cmd: code __WWM_CONFIG_PATH__
```
