### ISSUE TITLE
Windows Defender complains

### ISSUE THREAD

**Issue by fkjogu** [TimUntersberger/wwm#81]
With the current development exe, Windows Defender marks it as a virus "Behavior:Win32/Persistence.RU!ml". Do you have an idea what could cause that?

Also, awesome project! I look forward having an i3-alike on Windows. I don't know how people survive without a titling window manger :wink:

**Comment by TimUntersberger** [comment]
Has this happenend for you before the update?

**Comment by TimUntersberger** [comment]
Can you please send me your config?

**Comment by fkjogu** [comment]
That's weird, I cannot reproduce anymore. I am on Windows 10 Pro, 1909. Config below

<details>

```yaml
app_bar_font: Cascadia Mono
app_bar_font_size: 17

work_mode: true
multi_monitor: true
launch_on_startup: false
display_app_bar: true
remove_title_bar: false
remove_task_bar: true

# workspaces:
#   - id: 4
#     monitor: 1
#   - id: 5
#     monitor: 1

rules:
  - pattern: ^(File Explorer|Task Manager)$
    manage: true
  - pattern: ^.*- Mozilla Firefox|Mozilla Firefox$
    has_custom_titlebar: true
    firefox: true
  - pattern: ^.*- Slack|Slack$
    has_custom_titlebar: true
  - pattern: ^Spotify Premium$
    has_custom_titlebar: true
  - pattern: ^.*- Google Chrome$
    has_custom_titlebar: true
    chromium: true
  - pattern: ^.*- Visual Studio Code$
    has_custom_titlebar: true

keybindings:
  - type: Launch
    key: Alt+Enter
    cmd: wt.exe

  - type: CloseTile
    key: Alt+Q

  - type: Quit
    key: Alt+X

  - type: Focus
    key: Alt+H
    direction: Left
  - type: Focus
    key: Alt+J
    direction: Down
  - type: Focus
    key: Alt+K
    direction: Up
  - type: Focus
    key: Alt+L
    direction: Right

  - type: Swap
    key: Alt+Control+H
    direction: Left
  - type: Swap
    key: Alt+Control+J
    direction: Down
  - type: Swap
    key: Alt+Control+K
    direction: Up
  - type: Swap
    key: Alt+Control+L
    direction: Right

  - type: Split
    key: Alt+Plus
    direction: Vertical
  - type: Split
    key: Alt+Minus
    direction: Horizontal

  - type: ToggleFloatingMode
    key: Alt+Control+F
  - type: ToggleFullscreen
    key: Alt+F
  - type: ToggleWorkMode
    key: Alt+Control+W

  - type: MoveToWorkspace
    key: Alt+Shift+1
    id: 1
  - type: MoveToWorkspace
    key: Alt+Shift+2
    id: 2
  - type: MoveToWorkspace
    key: Alt+Shift+3
    id: 3
  - type: MoveToWorkspace
    key: Alt+Shift+4
    id: 4

  - type: MoveWorkspaceToMonitor
    key: Alt+Control+1
    monitor: 1
  - type: MoveWorkspaceToMonitor
    key: Alt+Control+2
    monitor: 2

  - type: ChangeWorkspace
    key: Alt+1
    id: 1
  - type: ChangeWorkspace
    key: Alt+2
    id: 2
  - type: ChangeWorkspace
    key: Alt+3
    id: 3
  - type: ChangeWorkspace
    key: Alt+4
    id: 4
  - type: ChangeWorkspace
    key: Alt+5
    id: 5
```
</details>
