### ISSUE TITLE
Support for custom date and time formats

### ISSUE THREAD

**Issue by keepitsane** [TimUntersberger/wwm#89]
Would be nice if we can style the clock and date in any custom format. As a simple option switching the clock from 24 hour format to 12 hour.

You could also make it more robust and take some inspiration from this Javascript package, just as an example of what I mean for custom formats: [https://momentjs.com/](https://momentjs.com/)

Suggested formatting could be something like this:
```
date:
  - pattern: MM DD

clock:
  - pattern: h:mm:ss a
```

Thanks!
