### ISSUE TITLE
Explore different config formats

### ISSUE THREAD

**Issue by TimUntersberger** [TimUntersberger/wwm#98]
The config file has already grown a lot and I feel like `yaml` slowly becomes a bit constraining, so I thought about ways to make the config feel better. Initially I looked at how i3 does its config, but I noticed that they built their own DSL and I am not willing to do this, so right now I am looking at including a lua interpreter into WWM (I got this idea from Neovim) to make it possible to configure WWM via a lua file.

I already experimented a bit with a possible DSL for the config file and right now it is looking like the following example

**Example Config**
```lua
enable { 
  "work_mode", 
  "launch_on_startup" 
}

set { "work_mode", true }
set { "min_height", 200 }

bind { "Alt+Enter", launch("wt.exe") }

for i=1,10 do
  bind { "Alt+" .. i, change_workspace(i) }
end

mode "resize" { 
  bind { "H", resize("Left", 2) },
  bind { "Shift+H", resize("Left", -2) },
}
```

It is possible to call functions in lua with paranthesis if the function takes only one argument and the argument is either a `table` or a `string`, so this makes the experience of writing the config a bit better.

One big plus for using an already established language for writing the config, would be having access to all the normal features of the language when writing your config.

There are still a lot of things I have to think about when designing the DSL. One example is whether to use curly braces or normal paranthesis for calling a WWM function.

**Example One**
```lua
  bind { "Alt+Enter", launch("wt.exe") }
```

**vs.**

```lua
  bind("Alt+Enter", launch("wt.exe"))
```

I think it would be possible to support both styles, but I am not sure whether it is worth it.

**Example two**
```lua
set { "work_mode", true }
```

**vs.**

```lua
set "work_mode" "true"
```

Another thing this could enable is running lua code when pressing a keybinding.

So instead of writing this
```lua
bind { "Alt+Enter", launch("wt.exe") }
```

You could write this
```lua
local function launchTerminal()
  -- code for launching wt.exe
end

bind { "Alt+Enter", callback(launchTerminal) }
```

I would integrate `lua` into WWM by using [rlua](https://github.com/amethyst/rlua)

Does anyone have any thoughts regarding this?

Here is the [REPL](https://repl.it/@TimUntersberger/WWM-lua-config#config.lua) I used to experiment with this a bit.

**Comment by TimUntersberger** [comment]
Another possible candidate would be [rhai](https://github.com/jonathandturner/rhai). Rhai was designed with DSL in mind and you can even define custom syntax.

**Rhai Config**
```rust
enable work_mode;
enable launch_on_startup;

set work_mode true;
set min_height 200;

bind "Alt+Enter" to launch("wt.exe");

for i in range(1,10) {
  let key = "Alt+" + i;
  bind key to change_workspace(i);
}

mode resize {
  bind "H" to resize("Left", 2);
  bind "Shift+H" to resize("Left", -2);
};

```

**Comment by TimUntersberger** [comment]
# Update

I played around with `rhai` and I think I will use it instead of lua.

I already implemented how to bind keybindings in the `rhai` branch.

**This is how my current rhai config looks like**
```
bind "Alt+Enter" launch("wt.exe");
bind "Alt+B" launch("C:\\Program Files\\Mozilla Firefox\\firefox.exe");

bind "Alt+Q" close_tile();
bind "Alt+M" minimize_tile();

bind "Alt+H" focus("Left");
bind "Alt+J" focus("Down");
bind "Alt+K" focus("Up");
bind "Alt+L" focus("Right");

bind "Alt+Control+H" swap("Left");
bind "Alt+Control+J" swap("Down");
bind "Alt+Control+K" swap("Up");
bind "Alt+Control+L" swap("Right");

bind "Alt+Plus" split("Vertical");
bind "Alt+Minus" split("Horizontal");

bind "Alt+Control+F" toggle_floating_mode();
bind "Alt+Control+W" toggle_work_mode();
bind "Alt+F" toggle_fullscreen();

bind_range 1 10 "Alt+Shift" move_to_workspace;
bind_range 1 10 "Alt+Control" move_workspace_to_monitor;
bind_range 1 10 "Alt" change_workspace;
```

**The same thing in yaml (with less number bindings)**

```yaml
  - type: Launch
    key: Alt+Enter
    cmd: wt.exe
  - type: Launch
    key: Alt+B
    cmd: C:\\Program Files\\Mozilla Firefox\\firefox.exe

  - type: CloseTile
    key: Alt+Q
  - type: MinimizeTile
    key: Alt+M

  - type: Quit
    key: Alt+X

  - type: Focus
    key: Alt+H
    direction: Left
  - type: Focus
    key: Alt+J
    direction: Down
  - type: Focus
    key: Alt+K
    direction: Up
  - type: Focus
    key: Alt+L
    direction: Right

  - type: Swap
    key: Alt+Control+H
    direction: Left
  - type: Swap
    key: Alt+Control+J
    direction: Down
  - type: Swap
    key: Alt+Control+K
    direction: Up
  - type: Swap
    key: Alt+Control+L
    direction: Right

  - type: Split
    key: Alt+Plus
    direction: Vertical
  - type: Split
    key: Alt+Minus
    direction: Horizontal

  - type: ToggleFloatingMode
    key: Alt+Control+F
  - type: ToggleFullscreen
    key: Alt+F
  - type: ToggleWorkMode
    key: Alt+Control+W

  - type: MoveToWorkspace
    key: Alt+Shift+1
    id: 1
  - type: MoveToWorkspace
    key: Alt+Shift+2
    id: 2
  - type: MoveToWorkspace
    key: Alt+Shift+3
    id: 3
  - type: MoveToWorkspace
    key: Alt+Shift+4
    id: 4

  - type: MoveWorkspaceToMonitor
    key: Alt+Control+1
    monitor: 1
  - type: MoveWorkspaceToMonitor
    key: Alt+Control+2
    monitor: 2

  - type: ChangeWorkspace
    key: Alt+1
    id: 1
  - type: ChangeWorkspace
    key: Alt+2
    id: 2
  - type: ChangeWorkspace
    key: Alt+3
    id: 3
  - type: ChangeWorkspace
    key: Alt+4
    id: 4
  - type: ChangeWorkspace
    key: Alt+5
    id: 5
```

I feel like the flexibility `rhai` provides is a huge plus for this direction and the readability improves by a lot too.
